export const MOCK_DATA_ITEM: any[] = [
    {
        "_id": "657c84db992625a8e769d6cf",
        "title": "Du lịch Tây Bắc mùa Hoa Cải Trắng - Hà Nội - Mộc Châu - Điện Biên từ Sài Gòn 2024",
        "ticket_ID": "16986  ",
        "trip": "Tây Bắc : Hà Nội - Mộc Châu - Cầu Kính Bạch Long - Điện Biên - Sapa - Fansipan",
        "price": "9,499,000 đ",
        "description": "Du lịch Tây Bắc mùa Hoa Cải Trắng - Hà Nội - Mộc Châu - Điện Biên từ Sài Gòn 2024. Mộc Châu đẹp nhất khi bước khoảng thời gian mùa hoa cải, đây cũng là thời điểm dân phượt nô nức kéo nhau lên Mộc Châu để chụp ảnh, ngắm hoa. Hoa cải ở Mộc Châu khi nở nó phủ trắng các thung lũng, các quả đồi, những sườn núi. Đi từ quốc lộ 6, Mộc Châu dần hiện ra trước mắt bạn như một thiên đường thực sự nằm giữa lưng chừng mây. Theo đó, vào những tháng cuối năm những cánh đồng hoa cải trắng Mộc Châu bắt đầu nở rộ thu hút rất đông khách thập phương. Lúc này, thời tiết cũng bắt đầu có sự rét nhẹ, kèm theo sương mù báo hiệu mùa hoa cải Mộc Châu đã đến và  làm cho cảnh sắc nơi đây càng thơ mộng hơn bao giờ hết. Hãy cùng Du Lịch Việt chúng tôi điểm qua vài nơi lý tưởng để có những thước phim và hình ảnh đẹp trong chuyến tour du lịch Mộc Châu mùa Hoa Cải Trắng này nhé! Thị trấn nông trường Mộc Châu, tại thị trấn nông trường Mộc Châu có rất nhiều cánh đồng hoa cải trắng. Mỗi thửa ruộng cách nhau không xa và thường rộng đến cả ngàn mét vuông nên bạn có thể tha hồ ngắm cảnh và chụp ảnh. Hay Thung lũng Nà Ka, Thung lũng Nà Ka vốn nổi tiếng với những vườn mơ, mận bạt ngàn. Vào mùa này, ngay dưới những gốc cây sần sùi, trơ trụi là những vườn cảnh trắng tinh khôi, tạo lên khung cảnh cực thơ mộng. ........",
        "departure_place": "Từ\nHồ Chí Minh  \n",
        "duration": "5 ngày 4 đêm",
        "vehicle": "\nXe du lịch, Máy bay  \n",
        "time_depart": "04,11,18,25/11; 02,09,26,23/12; 13,20,27/01/2024",
        "highlights": "Trải nghiệm: ✔️ Ghé thăm những nương chè xanh mướt tại nông trường Mộc Châu. ✔️ Checkin cầu kính Bạch Long – cây cầu kính dài nhất thế giới. ✔️ Thăm lại chiến trường xưa Điện Biên Phủ oai hùng, vang danh lịch sử. ✔️ Tham quan thị trấn sương mù Sapa  ",
        "service_des": "Giờ bay có thể thay đổi theo quy định của hàng không. Du Lịch Việt sẽ thay đổi chương trình cho phù hợp với giờ bay mới nhưng sẽ không chịu trách nhiệm về các khoản chi phí phát sinh.(Đoàn tối thiểu 10 khách khởi hành)Giá tour bao gồm:",
        "view": " 863",
        "url": "https://dulichviet.com.vn/du-lich-trong-nuoc/du-lich-tay-bac-mua-hoa-cai-trang-ha-noi-moc-chau-dien-bien-tu-sai-gon-2024?idschedule=97248",
        "image_url": "https://dulichviet.com.vn/images/bandidau/NOI-DIA/Moc-Chau/du-lich-tay-bac-mua-hoa-cai-trang-du-lich-viet(1).jpg"
      },
      {
        "_id": "657c84db992625a8e769d6d1",
        "title": "Du lịch Tây Bắc - Hà Nội - Mộc Châu - Điện Biên mùa Xuân từ Sài Gòn 2024",
        "ticket_ID": "17083  ",
        "trip": "Tây Bắc : Hà Nội - Mộc Châu - Cầu Kính Bạch Long - Điện Biên - Sapa - Fansipan",
        "price": "8,899,000 đ",
        "description": "Du lịch Tây Bắc - Hà Nội - Mộc Châu - Điện Biên mùa Xuân từ Sài Gòn 2024. Hành trình khám phá Mộc Châu - Cầu Kính Bạch Long - Điện Biên - Sapa - Fansipan chắc chắn sẽ là một hành trình đầy thú vị dành cho quý khách khi lựa chọn Du Lịch Việt chúng tôi là đơn vị đồng hành trong suốt hành trình. Hành trình này sẽ đưa bạn đến với Mộc Châu, Sơn La tại đây, bạn sẽ có cơ hội tham quan rất nhiều những danh lam thắng cảnh tuyệt mĩ như Đèo Pha Đin, Mường Phăng, đồi chè,... hay thưởng thức những món ăn đặc sản ngon nhất vùng như cơm lam, xôi ngũ sắc, trứng kiến,... hay được trải nghiệm tất cả những nét văn hóa đặc sắc và độc đáo của vùng đất này,... Tất cả những điều này bạn sẽ trải nghiệm trong hành trình Tour Mùa Xuân Tây Bắc đầy thú vị này khi đồng hành cùng chúng tôi! ",
        "departure_place": "Từ\nHồ Chí Minh  \n",
        "duration": "5 ngày 4 đêm",
        "vehicle": "\nXe du lịch, Máy bay  \n",
        "time_depart": "24,27/02; 02,09,16,23/03/2024",
        "highlights": "Trải nghiệm: ✔️ Ghé thăm những nương chè xanh mướt tại nông trường Mộc Châu. ✔️ Checkin cầu kính Bạch Long – cây cầu kính dài nhất thế giới. ✔️ Thăm lại chiến trường xưa Điện Biên Phủ oai hùng, vang danh lịch sử. ✔️ Tham quan thị trấn sương mù Sapa  ",
        "service_des": "Giờ bay có thể thay đổi theo quy định của hàng không. Du Lịch Việt sẽ thay đổi chương trình cho phù hợp với giờ bay mới nhưng sẽ không chịu trách nhiệm về các khoản chi phí phát sinh.(Đoàn tối thiểu 10 khách khởi hành)Giá tour bao gồm:",
        "view": " 640",
        "url": "https://dulichviet.com.vn/du-lich-trong-nuoc/du-lich-tay-bac-ha-noi-moc-chau-dien-bien-mua-xuan-tu-sai-gon-2024?idschedule=97506",
        "image_url": "https://dulichviet.com.vn/images/bandidau/NOI-DIA/Sapa/thung-lung-muong-hoa-tour-sapa-mua-thu-du-lich-viet.jpg"
      },
      {
        "_id": "657c84db992625a8e769d6d2",
        "title": "Du lịch Đông Bắc Hoa Tam Giác Mạch - Hà Nội - Hà Giang - Quản Bạ - Sông Nho Quế từ Sài Gòn 2024",
        "ticket_ID": "16988  ",
        "trip": "Đông Bắc: Hà Giang - Quản Bạ - Đồng Văn - Lũng Cú - Mèo Vạc - Sông Nho Quế",
        "price": "8,199,000 đ",
        "description": "Du lịch Đông Bắc Hoa Tam Giác Mạch - Hà Nội - Hà Giang - Quản Bạ - Sông Nho Quế  từ Sài Gòn 2024. HoaTam giác mạch, hay kiều mạch, lúa mạch đen (tiếng anh là buckwheat) là loại cây được trồng ở vùng núi cao phía Bắc Việt Nam. Cây này thuộc họ đậu (Fabaceae), cánh hoa chụm lại với nhau thành hình chóp, ở giữa là hạt mạch. Hoa Tam Giác Mạch từ lâu đã trở thành điểm nhấn thu hút đông đảo khách du lịch Hà Giang mỗi năm, đặc biệt là các bạn trẻ thích du lịch và đam mê khám phá. Vùng đất địa đầu Tổ Quốc, nơi được ví như “Đà Lạt thứ hai của Việt Nam” này có những dãy núi cao hun hút tận mây xanh, những khu rừng hoang sơ và Cao nguyên đá Đồng Văn rộng lớn, bát ngát. Bên cạnh đó, những cung đường trải dài, uốn lượn quanh những khu ruộng bậc thang trùng điệp cũng là điều hớp hồn bất cứ ai đến với Hà Giang lần đầu tiên. Hoa Tam Giác Mạch ở Hà Giang có sức hút riêng không lẫn đi đâu được. Những cánh hoa màu hồng phớt, tô điểm sắc tím mộng mơ khiến cả ngọn đồi như được phủ lên một thảm màu rực rỡ. Hoa mọc trên đồi, trên đường đi, ở chân núi, trên đèo và thậm chí mang sức sống mãnh liệt ấy lên cả những vách đá đầy chông gai hiểm nguy. Vì có sắc hoa Tam Giác Mạch, ngay đến cả thiên nhiên núi rừng hiểm trở cũng hóa dịu dàng.",
        "departure_place": "Từ\nHồ Chí Minh  \n",
        "duration": "4 ngày 3 đêm",
        "vehicle": "\nXe du lịch, Máy bay  \n",
        "time_depart": "01,08,15,22,29/11; 06/12/2023; 10,17,24/01/2024",
        "highlights": "Trải nghiệm: ✔️ Chinh phục đèo Mã Pì Lèng – nơi được mệnh danh “Nam thiên đệ nhất đèo”. ✔️ Checkin Sông Nho Quế siêu hot. ✔️ Thưởng thức nền ẩm thực phong phú tại phố cổ Đồng Văn  ",
        "service_des": "Giờ bay có thể thay đổi theo quy định của hàng không. Du Lịch Việt sẽ thay đổi chương trình cho phù hợp với giờ bay mới nhưng sẽ không chịu trách nhiệm về các khoản chi phí phát sinh.(Đoàn tối thiểu 10 khách khởi hành)Giá tour bao gồm:",
        "view": " 487",
        "url": "https://dulichviet.com.vn/du-lich-trong-nuoc/du-lich-dong-bac-hoa-tam-giac-mach-ha-noi-ha-giang-quan-ba-song-nho-que-tu-sai-gon-2024?idschedule=96572",
        "image_url": "https://dulichviet.com.vn/images/bandidau/NOI-DIA/Ha-Giang/du-lich-ha-giang-mua-hoa-tam-giac-mach-du-lich-viet.jpg"
      },
      {
        "_id": "657c84db992625a8e769d6d3",
        "title": "Du lịch Tây Bắc mùa Hoa Cải Trắng - Hà Nội - Mộc Châu - Điện Biên - Sapa 6N5Đ từ Sài Gòn 2024",
        "ticket_ID": "16987  ",
        "trip": "Tây Bắc: Hà Nội - Mộc Châu - Cầu Kính Bạch Long - Sơn La - Điện Biên - Sapa - Đền Hùng",
        "price": "9,899,000 đ",
        "description": "Du lịch Tây Bắc mùa Hoa Cải Trắng - Hà Nội - Mộc Châu - Điện Biên - Sapa 6N5Đ từ Sài Gòn 2024. Mộc Châu vào những mùa hoa luôn để lại những dấu ấn không thể phai nhòa trong ánh mắt và niềm thương của khách du lịch thập phương. Trong những mùa hoa nở rộ và đong đầy ấy, có lẽ mùa hoa cải trắng là ấn tượng hơn cả. Du lịch Mộc Châu mùa hoa cải trắng, du khách sẽ được chiêm ngưỡng những cánh đồng hoa cải rực rỡ khắp bản làng, thung lũng và thỏa thích check-in, chụp ảnh trong một khung cảnh đẹp như mơ, như họa. Hãy cùng Du Lịch Việt tìm hiểu và khám phá mùa hoa cải trắng ở Mộc Châu để hiểu được vẻ đẹp này và thêm mãn nhãn nhé!",
        "departure_place": "Từ\nHồ Chí Minh  \n",
        "duration": "6 ngày 5 đêm",
        "vehicle": "\nXe du lịch, Máy bay  \n",
        "time_depart": "07,14,21,28/11; 05,12,19/12/2023 ; 09,16,21,23/01/2024",
        "highlights": "",
        "service_des": "Giờ bay có thể thay đổi theo quy định của hàng không. Du Lịch Việt sẽ thay đổi chương trình cho phù hợp với giờ bay mới nhưng sẽ không chịu trách nhiệm về các khoản chi phí phát sinh. (Đoàn tối thiểu 10 khách khởi hành) Giá tour bao gồm:",
        "view": " 469",
        "url": "https://dulichviet.com.vn/du-lich-trong-nuoc/du-lich-tay-bac-mua-hoa-cai-trang-ha-noi-moc-chau-dien-bien-sapa-6n5d-tu-sai-gon-2024?idschedule=96563",
        "image_url": "https://dulichviet.com.vn/images/bandidau/NOI-DIA/Moc-Chau/du-lich-moc-chau-mua-hoa-cai-trang-du-lich-viet.jpg"
      }
];

export const MOCK_DATA_ITEM2: any[] = [
    {
        "_id": "657c84db992625a8e769d6da",
        "title": "Du lịch Đông Bắc Tết Dương lịch - Hà Nội - Hà Giang - Quản Bạ từ Sài Gòn 2024",
        "ticket_ID": "16922  ",
        "trip": "Đông Bắc: Hà Giang - Quản Bạ - Đồng Văn - Lũng Cú - Mèo Vạc - Sông Nho Quế",
        "price": "9,899,000 đ",
        "description": "Du lịch Đông Bắc Tết Dương lịch - Hà Nội - Hà Giang - Quản Bạ từ Sài Gòn 2024. Đông Bắc Bộ là khu vực nằm ở phía bắc Việt Nam bao gồm 9 tỉnh: Hà Giang, Cao Bằng, Bắc Kạn, Lạng Sơn, Tuyên Quang, Thái Nguyên, Phú Thọ, Bắc Giang, Quảng Ninh. Không thua kém vẻ yêu kiều mùa xuân của Tây Bắc, Đông Bắc có những bức tranh núi rừng tràn ngập màu sắc và sức sống của con người. Nó mang lại niềm tự hào và kinh tế du lịch cho con người nơi đây. Với những cao nguyên núi đá không quá cao, Hà Giang thu hút ánh mắt đầu tiên của người tham quan. Ngàn năm nay, Hà Giang vẫn như thế, bình dị hoang sơ nhưng không kém phần thu hút. Là một trong những điểm đến trong tour du lịch Đông Bắc Tết được đông đảo du khách tìm đến khám phá. Không những vậy, sự hoang sơ, tự nhiên đó lại càng ngày càng làm động lòng người. Đứng trên khu vực cột cờ Lũng Cú, bạn sẽ có cảm giác như đứng trước Tổ quốc thân yêu, ôm cả không gian đó vào lòng mình. Mùa xuân đến, du lịch Đông Bắc – Hà Giang lại càng thêm náo nhiệt bởi sự khoe sắc của hoa cỏ núi rừng. Như một sự háo hức đón chuẩn bị đón năm mới, mừng các lễ hội, muôn hoa Hà Giang cùng nhau đua nở. Màu hồng hoa đào, trắng hoa mận đến màu vàng hoa cải như réo rắt người xem mau mau đến. Mùa tết, trên khắp các bản làng Hà Giang náo nhiệt các âm thanh chào mừng của lễ hội. Những tiếng hát du dương của các cặp đôi, tiếng của các nhạc cụ dân tộc cùng với âm thanh tự nhiên cùng làm nóng lên không khí mùa đông tour Đông Bắc Tết, ấm lòng mỗi du khách tham quan. Có rất nhiều địa điểm tham quan khi tham gia tour Đông Bắc – Hà Giang như núi đôi Quản Bạ, đèo Mã Pí Lèng, ruộng bậc thang Yên Minh - Sủng Là, cửa khẩu Thanh Thủy, phố Đồng Văn, ...Không chỉ được thiên nhiên ưu ái ban tặng cho nhiều danh lam thắng cảnh đẹp khiến cả thế giới trầm trồ mà Hà Giang còn nổi tiếng là nơi lưu giữ những di tích lịch sử lâu đời cũng như những nét đẹp văn hóa đặc sắc của 22 dân tộc vùng cao phía Bắc. Tất cả đã tạo nên sức hút vô cùng hấp dẫn khiến các tín đồ du lịch không thể nào ngừng tìm du lịch mùa Thu trong nước tại Hà Giang để có thể khám phá vùng sơn cước xinh đẹp này. ",
        "departure_place": "Từ\nHồ Chí Minh  \n",
        "duration": "4 ngày 3 đêm",
        "vehicle": "\nXe du lịch, Máy bay  \n",
        "time_depart": "29,30/12/2023 ",
        "highlights": "Trải nghiệm: ✔️ Chinh phục đèo Mã Pì Lèng – nơi được mệnh danh “Nam thiên đệ nhất đèo”. ✔️ Checkin Sông Nho Quế siêu hot. ✔️ Thưởng thức nền ẩm thực phong phú tại phố cổ Đồng Văn.  ",
        "service_des": "Giờ bay có thể thay đổi theo quy định của hàng không. Du Lịch Việt sẽ thay đổi chương trình cho phù hợp với giờ bay mới nhưng sẽ không chịu trách nhiệm về các khoản chi phí phát sinh.(Đoàn tối thiểu 10 khách khởi hành)Giá tour bao gồm:",
        "view": " 154",
        "url": "https://dulichviet.com.vn/du-lich-trong-nuoc/du-lich-dong-bac-tet-duong-lich-ha-noi-ha-giang-quan-ba-tu-sai-gon-2024?idschedule=95254",
        "image_url": "https://dulichviet.com.vn/images/bandidau/NOI-DIA/Quan-Ba/cot-co-lung-cu-du-lich-viet.jpg"
      },
      {
        "_id": "657c84db992625a8e769d6dc",
        "title": "Du lịch Tết Dương lịch - Hà Nội - Mai Châu - Mộc Châu - Ninh Bình - Tràng An từ Sài Gòn 2024",
        "ticket_ID": "16925  ",
        "trip": "Mai Châu - Mộc Châu - Ninh Bình - Chùa Bái Đính - Tràng An",
        "price": "9,899,000 đ",
        "description": "Du lịch Tết Dương lịch - Hà Nội - Mai Châu - Mộc Châu - Ninh Bình - Tràng An từ Sài Gòn 2024. Độc đáo với quang cảnh thiên nhiên hoang sơ, non nước hữu tình, Ninh Bình hiện nay đang là điểm đến du lịch nổi tiếng ở khu vực miền Bắc nước ta. Đây cũng là một trong những địa danh có lượng khách du lịch tham quan lớn số 1. Cách thủ đô Hà Nội  khoảng tầm 100km về phía Nam, tỉnh Ninh Bình có địa phận thuộc đồng bằng Bắc Bộ. Các địa điểm du lịch ở Ninh Bình không chỉ có phỏng cảnh đẹp mà nơi đây còn chứa đựng ý nghĩa lịch sử hào hùng của cả dân tộc, nên ngoài việc thu hút được hàng trăm nghìn lượt khách quốc tế mỗi năm, nơi đây còn là thắng cảnh được ưa chuộng của rất nhiều bạn trẻ yêu thích du lịch tại Việt Nam. Tràng An Cố đô Hoa Lư là quần thể di tích lịch sử đất nước đặc biệt quan trọng của nước ta. Đây cũng là một trong bốn vùng lõi của quần thể di sản thế giới Tràng An đã được UNESCO công nhận. Mạng lưới hệ thống di tích lịch sử ở Hoa Lư có liên quan đến công danh của rất nhiều nhân vật lịch sử hào hùng thuộc ba triều đại nhà Đinh, nhà Tiền Lê và giai đoạn đầu nhà Lý, tính từ Đinh Tiên Hoàng đến Lý Thái Tông.",
        "departure_place": "Từ\nHồ Chí Minh  \n",
        "duration": "4 ngày 3 đêm",
        "vehicle": "\nXe du lịch, Máy bay  \n",
        "time_depart": "29,30/12/2023",
        "highlights": "Trải nghiệm: ✔️ Ghé thăm những nương chè xanh mướt tại nông trường Mộc Châu. ✔️ Checkin cầu kính Bạch Long – cây cầu kính dài nhất thế giới. ✔️ Xuôi thuyền dọc theo giữa cánh đồng lúa thăm Khu du lịch Tràng An. ✔️ Viếng chùa Bái Đính  – ngôi chùa có nhiều kỷ lục nhất Việt Nam.",
        "service_des": "Giờ bay có thể thay đổi theo quy định của hàng không. Du Lịch Việt sẽ thay đổi chương trình cho phù hợp với giờ bay mới nhưng sẽ không chịu trách nhiệm về các khoản chi phí phát sinh. Giá tour bao gồm:",
        "view": " 159",
        "url": "https://dulichviet.com.vn/du-lich-trong-nuoc/du-lich-tet-duong-lich-ha-noi-mai-chau-moc-chau-ninh-binh-trang-an-tu-sai-gon-2024?idschedule=95276",
        "image_url": "https://dulichviet.com.vn/images/bandidau/NOI-DIA/Ninh-Binh/trang-an-du-lich-viet.jpg"
      },
      {
        "_id": "657c84db992625a8e769d6dd",
        "title": "Du lịch Đông Bắc Tết Dương lịch 2024 - Hà Nội - Hà Giang - Cao Bằng - Sông Nho Quế từ Sài Gòn",
        "ticket_ID": "16928  ",
        "trip": "Đông Bắc: Hà Nội - Hà Giang - Đồng Văn - Lũng Cú - Mèo Vạc - Cao Bằng - Thác Bản Giốc - Sông Nho Quế",
        "price": "11,399,000 đ",
        "description": "Du lịch Đông Bắc Tết Dương lịch 2024 - Hà Nội - Hà Giang - Cao Bằng - Sông Nho Quế từ Sài Gòn. Tour du lịch Đông Bắc - cùng Du Lịch Việt sẽ đưa du khách đến không gian xanh mát của núi rừng. Hành trình du lịch Đông Bắc, đưa du khách tham quan những thắng cảnh đồi núi trùng điệp hùng vĩ, hay những thác nước chảy cuồn cuộn, những cảnh thiên nhiên thơ mộng, hay sự nhộn nhịp của những con phố cổ. ",
        "departure_place": "Từ\nHồ Chí Minh  \n",
        "duration": "5 ngày 4 đêm",
        "vehicle": "\nXe du lịch, Máy bay  \n",
        "time_depart": "28,29,30/12/2023",
        "highlights": "Trải nghiệm: ✔️ Chinh phục đèo Mã Pì Lèng – nơi được mệnh danh “Nam thiên đệ nhất đèo”. ✔️ Checkin Sông Nho Quế siêu hot. ✔️ Ngoạn cảnh Thác Bản Giốc đẹp như tranh vẽ. ✔️ Thưởng thức nền ẩm thực phong phú tại phố cổ Đồng Văn.",
        "service_des": "Giờ bay có thể thay đổi theo quy định của hàng không. Du Lịch Việt sẽ thay đổi chương trình cho phù hợp với giờ bay mới nhưng sẽ không chịu trách nhiệm về các khoản chi phí phát sinh. (Đoàn tối thiểu 10 khách khởi hành)Giá tour bao gồm:",
        "view": " 208",
        "url": "https://dulichviet.com.vn/du-lich-trong-nuoc/du-lich-dong-bac-tet-duong-lich-2024-ha-noi-ha-giang-cao-bang-song-nho-que-tu-sai-gon?idschedule=95307",
        "image_url": "https://dulichviet.com.vn/images/bandidau/NOI-DIA/Thac-Ban-Gioc/thac-ban-gioc-tet-du-lich-viet.jpg"
      },
      {
        "_id": "657c84db992625a8e769d6e2",
        "title": "Du lịch Hà Nội mùa Thu - Yên Tử - Hạ Long - Sapa bay Vietnam Airlines từ Sài Gòn 2023",
        "ticket_ID": "16756  ",
        "trip": "Hà Nội - Yên Tử - Hạ Long - Bắc Ninh - Đền Đô - Ninh Bình - Chùa Bái Đính - Tràng An - Sapa - Chinh phục đỉnh Fansipan",
        "price": "9,599,000 đ",
        "description": "",
        "departure_place": "Từ\nHồ Chí Minh  \n",
        "duration": "6 ngày 5 đêm",
        "vehicle": "\nXe du lịch, Máy bay  \n",
        "time_depart": "25/10/2023",
        "highlights": "",
        "service_des": "Giờ bay có thể thay đổi theo quy định của hàng không. Du Lịch Việt sẽ thay đổi chương trình cho phù hợp với giờ bay mới nhưng sẽ không chịu trách nhiệm về các khoản chi phí phát sinh. Giá tour bao gồm:",
        "view": " 574",
        "url": "https://dulichviet.com.vn/du-lich-trong-nuoc/du-lich-ha-noi-mua-thu-yen-tu-ha-long-sapa-bay-vietnam-airlines-tu-sai-gon-2023?idschedule=92585",
        "image_url": "https://dulichviet.com.vn/images/bandidau/NOI-DIA/Ninh-Binh/du-lich-vinh-ha-long-tet-am-lich-du-lich-viet.jpg"
      }
]